### Create Singular
POST http://127.0.0.1:8000/posts
Content-Type: application/json

{
  "title": "Some title",
  "author": "Smith"
}
> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}
###
POST http://127.0.0.1:8000/comments
Content-Type: application/json

{
  "postId": 1,
  "body": "My Comment",
  "author": "Smith"
}
> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}
###
POST http://127.0.0.1:8000/profiles
Content-Type: application/json

{
  "name": "Mary",
  "email": "mary.smith@company.com"
}
### Get Plurals
GET http://127.0.0.1:8000/posts
Accept: application/json

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}
###
GET http://127.0.0.1:8000/comments
Accept: application/json

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}
###
GET http://127.0.0.1:8000/profiles
Accept: application/json

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}
### Get Singular
GET http://127.0.0.1:8000/posts/0
Accept: application/json

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}
###
GET http://127.0.0.1:8000/comments/0

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}
###
GET http://127.0.0.1:8000/profiles/0

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}
### Delete Singular
DELETE http://127.0.0.1:8000/posts/0

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}
###
DELETE http://127.0.0.1:8000/comments/0

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}
###
DELETE http://127.0.0.1:8000/profiles/0

> {%
client.test("Request executed successfully", function() {
client.assert(response.status === 200, "Response status is not 200");
});
%}